openapi: "3.1.0"
info:
  description: "все операции взаимодействия с rest API"
  title: "Данный сервис определяет все операции взаимодействия с rest API"
  version: "1.0.0"
  contact:
    email: "secret@yandex.ru"
paths:
  /api/v1/users/register:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpDto"
        description: "Входные данные"
        required: true
      description: "Регистрация пользователя"
      tags:
        - "Регистрация"

  /api/v1/users/login:
    post:
      requestBody:
        $ref: "#/components/requestBodies/SignInDto"
      description: "Авторизация пользователя"
      tags:
        - "Авторизация"

  /api/v1/blogs/Blogs:
    get:
      requestBody:
        $ref: "#/components/requestBodies/GetAllBlogsDto"
      description: "Получение блогов"
      tags:
        - "Получение блогов"
  
servers:
  - url: "http://localhost:3000"
  - url: "https://localhost:3000"
components:
  requestBodies:
    SignInDto:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SignInDto"
      description: "Входные данные"
      required: true
  schemas:
    SignInDto:
      required:
        - "email"
        - "password"
      properties:
        email:
          type: "string"
          description: ""
        password:
          type: "string"
          description: ""
    SignUpDto:
      required:
        - "name"
        - "email"
        - "password"
      properties:
        name:
          type: "string"
          description: ""
        email:
          type: "string"
          description: ""
        password:
          type: "string"
          description: ""

  schemas:
    GetAllBlogssDto:
      properties:
        title:
          type: "string"
          description: ""
        content:
          type: "string"
          description: ""
        image:
          type: "string"
          description: ""
        author:
          type: "string"
          description: ""
        category:
          type: "string"
          description: ""
    GetAllBlogsDto:
      required:
        - "title"
        - "content"
        - "image"
        - "author"
        - "category"
      properties:
        title:
          type: "string"
          description: ""
        content:
          type: "string"
          description: ""
        image:
          type: "string"
          description: ""
        author:
          type: "string"
          description: ""
        category:
          type: "string"
          description: ""
        created_at:
          type: "string"
          description: ""
